# Generated by Django 3.2.4 on 2021-07-11 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='profit',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
