# Generated by Django 3.2.4 on 2021-07-13 11:05

from django.db import migrations, models
import recorder.models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to=recorder.models.to_upload),
        ),
    ]
