# Generated by Django 3.2.4 on 2021-06-14 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0004_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='percentage',
        ),
    ]
