# Generated by Django 3.2.4 on 2021-07-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0005_alter_collection_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
