# Generated by Django 3.2.4 on 2021-06-28 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0007_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.CreateModel(
            name='GasFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('fee', models.FloatField()),
            ],
        ),
    ]
