# Generated by Django 3.2.4 on 2021-07-08 06:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recorder', '0012_alter_inventory_available_quantity'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Suggestion',
        ),
        migrations.RenameField(
            model_name='downvote',
            old_name='post',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='like',
            old_name='post',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='upvote',
            old_name='post',
            new_name='suggestion',
        ),
    ]
