# Generated by Django 3.2.4 on 2021-07-09 11:09

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recorder', '0016_auto_20210709_1038'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('by', 'suggestion')},
        ),
    ]
