# Generated by Django 3.2.4 on 2021-07-09 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recorder', '0017_alter_like_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='downvote',
            unique_together={('by', 'suggestion')},
        ),
        migrations.AlterUniqueTogether(
            name='upvote',
            unique_together={('by', 'suggestion')},
        ),
    ]
