# Generated by Django 3.2.4 on 2021-06-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_alter_transaction_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='note',
            field=models.CharField(max_length=2000, null=True),
        ),
    ]
