# Generated by Django 3.2.4 on 2021-06-14 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0006_transaction_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='timestamp',
            field=models.DateField(null=True),
        ),
    ]
