# Generated by Django 3.2.4 on 2021-06-28 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0008_gasfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='gasfee',
            name='currency',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
