# Generated by Django 3.2.4 on 2021-07-02 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0010_auto_20210702_1154'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='profit',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='available_quantity',
            field=models.IntegerField(null=True),
        ),
    ]
